# Generated by Django 3.2.8 on 2021-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolsnap', '0002_alter_license_license_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
    ]
