# Generated by Django 3.2.8 on 2021-10-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsnap', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='license',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='resource',
            managers=[
            ],
        ),
    ]
