# Generated by Django 3.2.8 on 2021-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolsnap', '0004_auto_20211014_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
    ]
