# Generated by Django 3.2.8 on 2021-10-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolsnap', '0007_alter_item_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('user', 'item')},
        ),
    ]
